[package]
name = "solana-test-framework"
version = "1.14.0"
edition = "2021"
authors = ["lowprivuser"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
anchor = ["anchor-lang"]

[dependencies]
solana-program-test = "1.14.0"
solana-sdk = "1.14.0"
solana-program ="1.14.0"
solana-banks-client = "1.14.0"
solana-program-runtime = "1.14.0"
solana-client = "1.14.0"
spl-token = "3.5.0"
spl-associated-token-account = "1.1.2"
anchor-lang = { version = "0.26.0", optional = true }
async-trait = "0.1.52"
futures = "0.3"
borsh = "0.9"
bincode = "1.3.3"
log = "0.4"
chrono-humanize = "0.2"

[dev-dependencies]
program-for-tests = {path="tests/artifacts/program_for_tests"}
solana-test-validator = "1.14.0"